name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
      
    - name: Docker login
      env:
        DOCKER_USER: ${{ secrets.DOCKER_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    
    - name: Generate semantic version
      id: semantic-version
      uses: paulhatch/semantic-version@v4.0.3
      with:
        major_pattern: "major: "
        minor_pattern: "feat: "
        format: "${major}.${minor}.${patch}-prerelease${increment}"

    - name: Build Docker image
      env:
        NEW_VERSION: ${{ steps.semantic-version.outputs.version }}
      run: |
        docker build -t juank1520/docker-graphql:$NEW_VERSION .
        docker build -t juank1520/docker-graphql:latest .
    
    - name: Push Docker image
      run: |
        docker push juank1520/docker-graphql:$NEW_VERSION
        docker push juank1520/docker-graphql:latest

      

    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)




